### ISSUE TITLE
hector_mapping does not launch

### ISSUE THREAD

**Issue by Fran-FC** [RRL-ALeRT/hector_slam_ros2#3]
When launching `ros2 launch hector_mapping mapping_default.launch --debug`

I get this error: 

```
[DEBUG] [launch.launch_context]: emitting event synchronously: 'launch.events.IncludeLaunchDescription'
[INFO] [launch]: All log files can be found below /home/fran/.ros/log/2023-06-06-11-34-58-056647-fran-msi-5926
[INFO] [launch]: Default logging verbosity is set to DEBUG
[DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7fb77bf01b70>'
[DEBUG] [launch]: processing event: '<launch.events.include_launch_description.IncludeLaunchDescription object at 0x7fb77bf01b70>' ✓ '<launch.event_handlers.on_include_launch_description.OnIncludeLaunchDescription object at 0x7fb77bf2e8c0>'
[DEBUG] [launch]: An exception was raised in an async action/event
[DEBUG] [launch]: Traceback (most recent call last):
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 54, in get_launch_description_from_any_launch_file
    return loader(launch_file_path)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_description_sources/frontend_launch_file_utilities.py", line 35, in get_launch_description_from_frontend_launch_file
    return parser.parse_description(root_entity)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/frontend/parser.py", line 133, in parse_description
    actions = [self.parse_action(child) for child in entity.children]
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/frontend/parser.py", line 133, in <listcomp>
    actions = [self.parse_action(child) for child in entity.children]
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/frontend/parser.py", line 110, in parse_action
    return instantiate_action(entity, self)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/frontend/expose.py", line 39, in instantiate_action
    action_type, kwargs = action_parse_methods[entity.type_name](entity, parser)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/frontend/expose.py", line 105, in wrapper
    ret = found_parse_method(entity, parser)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch_ros/actions/node.py", line 328, in parse
    kwargs['executable'] = parser.parse_substitution(entity.get_attr('exec'))
  File "/opt/ros/humble/lib/python3.10/site-packages/launch_xml/entity.py", line 119, in get_attr
    raise attr_error
AttributeError: Attribute exec of type <class 'str'> not found in Entity node

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_service.py", line 336, in run_async
    raise completed_tasks_exceptions[0]
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_service.py", line 230, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_service.py", line 250, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/actions/include_launch_description.py", line 148, in execute
    launch_description = self.__launch_description_source.get_launch_description(context)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_description_source.py", line 84, in get_launch_description
    self._get_launch_description(self.__expanded_location)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_description_sources/any_launch_description_source.py", line 53, in _get_launch_description
    return get_launch_description_from_any_launch_file(location)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 57, in get_launch_description_from_any_launch_file
    raise InvalidLaunchFileError(extension, likely_errors=exceptions)
launch.invalid_launch_file_error.InvalidLaunchFileError: Caught exception when trying to load file of format [launch]: Attribute exec of type <class 'str'> not found in Entity node

[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught exception when trying to load file of format [launch]: Attribute exec of type <class 'str'> not found in Entity node
```

**Comment by skpawar1305** [comment]
ros2 run hector_mapping hector_mapping_node
also, we don't use this package anymore, so didn't bother to create a launch file

**Comment by Fran-FC** [comment]
Thanks! is there any particular reason why you don't use Hector SLAM anymore? I am working on a master's thesis analyzing and benchmark SLAM algorithms

**Comment by skpawar1305** [comment]
> Thanks! is there any particular reason why you don't use Hector SLAM anymore? I am working on a master's thesis analyzing and benchmark SLAM algorithms 

we create 3D octomap now
